spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-springboot-mybatis
    username: postgres
    password: 123456

mybatis:
  type-aliases-package: com.fengwenyi.springboot.mybatis.entity
  mapper-locations: classpath:mapper/*.xml